/*
 * FrontGUI.java
 *
 * Created on June 23, 2007, 8:46 PM
 */

package eunomia.plugin.gui.feedBack;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author  Mikhail Sosonkin
 */
public class FrontGUI extends javax.swing.JPanel {
    private Main main;
    private static Logger logger;
    
    static {
        logger = Logger.getLogger(FrontGUI.class);
    }
    
    /** Creates new form FrontGUI */
    public FrontGUI(Main main) {
        this.main = main;
        initComponents();
        
        Timer timer = new Timer();
        timer.schedule(new TimerTask(){
            public void run() {
                updatePage();
            }
        }, 2000, 1000*60);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JLabel jLabel1;
        javax.swing.JLabel jLabel2;
        javax.swing.JLabel jLabel4;
        javax.swing.JPanel jPanel1;
        javax.swing.JPanel jPanel2;
        javax.swing.JPanel jPanel3;
        javax.swing.JPanel jPanel4;
        javax.swing.JPanel jPanel5;
        javax.swing.JScrollPane jScrollPane1;
        javax.swing.JScrollPane respAreaScroll;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reqField = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        signature = new javax.swing.JTextField();
        affiliation = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        respAreaScroll = new javax.swing.JScrollPane();
        respArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("New Messages"));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Ask us a question or write a comment:");
        jPanel1.add(jLabel1, java.awt.BorderLayout.NORTH);

        jScrollPane1.setAutoscrolls(true);
        reqField.setColumns(20);
        reqField.setLineWrap(true);
        reqField.setRows(15);
        reqField.setText("Write text here.");
        jScrollPane1.setViewportView(reqField);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel4.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Signature:");
        jPanel4.add(jLabel2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Affiliation:");
        jPanel4.add(jLabel4);

        jPanel2.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        signature.setText("User");
        jPanel5.add(signature);

        affiliation.setText("A company Using NABS");
        jPanel5.add(affiliation);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        sendButton.setFont(new java.awt.Font("Tahoma", 0, 16));
        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        jPanel2.add(sendButton, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Responses"));
        respArea.setColumns(20);
        respArea.setEditable(false);
        respArea.setLineWrap(true);
        respArea.setRows(5);
        respAreaScroll.setViewportView(respArea);

        jPanel3.add(respAreaScroll, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        try {
            main.doPost(signature.getText(), affiliation.getText(), reqField.getText());
            updatePage();
        } catch (Exception ex) {
            logger.error("Submit Failed. Please try again later (" + ex.getMessage() + ")");
        }
    }//GEN-LAST:event_sendButtonActionPerformed
    
    private void updatePage() {
        new Thread(new Runnable() {
            public void run() {
                try {
                    respArea.setText(main.getList());
                } catch (Exception ex) {
                }
            }
        }).start();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField affiliation;
    javax.swing.JTextArea reqField;
    javax.swing.JTextArea respArea;
    javax.swing.JButton sendButton;
    javax.swing.JTextField signature;
    // End of variables declaration//GEN-END:variables
    
}
