/*
 * ConfigPanel.java
 *
 * Created on December 16, 2006, 10:33 PM
 */

package eunomia.plugin.gui.networkPolicy;

/**
 *
 * @author  kulesh
 */
public class ConfigPanel extends javax.swing.JPanel {
    
    /** Creates new form ConfigPanel */
    public ConfigPanel() {
        initComponents();
    }
    
    public int getRateSlider(){
        return (rateSlider.getValue());
    }
    
    public void setRateSlider(int v){
        rateSlider.setValue(v);
    }
    
    public int getTimeoutSlider(){
        return (timeoutSlider.getValue());
    }

    public void setTimeoutSlider(int v){
        timeoutSlider.setValue(v);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        rateLabel = new javax.swing.JLabel();
        timeoutLabel = new javax.swing.JLabel();
        timeoutSlider = new javax.swing.JSlider();
        rateSlider = new javax.swing.JSlider();
        rateValueLabel = new javax.swing.JLabel();
        timeoutValueLabel = new javax.swing.JLabel();

        setToolTipText("Slide to change the timeout of flows");
        setName("Configuration");
        rateLabel.setText("Flow Rate");

        timeoutLabel.setText("Flow Timeout");

        timeoutSlider.setMajorTickSpacing(10);
        timeoutSlider.setMaximum(120);
        timeoutSlider.setMinimum(10);
        timeoutSlider.setMinorTickSpacing(5);
        timeoutSlider.setPaintTicks(true);
        timeoutSlider.setToolTipText("Slide to change timeout of flows");
        timeoutSlider.setValue(0);
        timeoutSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                setTimeoutValueLabel(evt);
            }
        });

        rateSlider.setMajorTickSpacing(250);
        rateSlider.setMaximum(1000);
        rateSlider.setMinimum(50);
        rateSlider.setMinorTickSpacing(50);
        rateSlider.setPaintTicks(true);
        rateSlider.setToolTipText("Slide to change the flow bit rate");
        rateSlider.setValue(0);
        rateSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                setRateValueLabel(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(rateLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(rateSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(timeoutLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(timeoutSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(rateValueLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(timeoutValueLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {rateValueLabel, timeoutValueLabel}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {rateLabel, timeoutLabel}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(79, 79, 79)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(rateLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rateSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rateValueLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(timeoutValueLabel)
                        .addContainerGap())
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(timeoutLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .add(81, 81, 81))
                        .add(layout.createSequentialGroup()
                            .add(timeoutSlider, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap()))))
        );

        layout.linkSize(new java.awt.Component[] {timeoutLabel, timeoutSlider, timeoutValueLabel}, org.jdesktop.layout.GroupLayout.VERTICAL);

        layout.linkSize(new java.awt.Component[] {rateLabel, rateSlider, rateValueLabel}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents

    private void setTimeoutValueLabel(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_setTimeoutValueLabel
        timeoutValueLabel.setText(Integer.toString(timeoutSlider.getValue())+"Seconds");
    }//GEN-LAST:event_setTimeoutValueLabel

    private void setRateValueLabel(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_setRateValueLabel
        rateValueLabel.setText(Integer.toString(rateSlider.getValue())+"Kbps");
    }//GEN-LAST:event_setRateValueLabel
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel rateLabel;
    private javax.swing.JSlider rateSlider;
    private javax.swing.JLabel rateValueLabel;
    private javax.swing.JLabel timeoutLabel;
    private javax.swing.JSlider timeoutSlider;
    private javax.swing.JLabel timeoutValueLabel;
    // End of variables declaration//GEN-END:variables
    
}
